# Generated by Django 5.2.3 on 2025-12-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglistitem',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
